'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million (value not excees 4000000), find the sum of the even-valued terms.
'''

fib = 2
prevfib=1
tempfib=0
sum = 2
while(fib <=4000000):

    tempfib = fib #2
    fib += prevfib #2+1=3
    prevfib= tempfib #2
    if (fib %2 ==0):
        sum +=fib
    print(fib)
print("sum: ")
print(sum)

